baseURL = 'https://kikyo0x.github.io/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-cn'
title = 'Kikyo0x 的空间'
theme = 'FixIt'

# 是否开启 emoji 标签
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[params]
  version = "0.3.X"
  description = "Kikyo0x 的个人博客"
  keywords = ["Blog", "Kikyo0x", "Hugo", "FixIt"]

  # 全局默认作者配置
  [params.author]
    name = "Kikyo0x"
    email = "kikyo0x@users.noreply.github.com"
    link = "https://github.com/Kikyo0x"
    avatar = "https://github.com/Kikyo0x.png"

  # 页头配置
  [params.header]
    [params.header.title]
      name = "Kikyo0x"

  # 首页配置
  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "https://github.com/Kikyo0x.png"
      title = "Kikyo0x"
      subtitle = "架构 / 极客 / 个人主页"
      typeit = true

      [params.home.profile.social]
        GitHub = "Kikyo0x"

  # 代码块配置
  [params.code]
    copy = true
    maxShownLines = 30

[markup]
  # 语法高亮 (FixIt 主题必要配置: https://github.com/hugo-fixit/FixIt/issues/43)
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    guessSyntax = true
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = false
      table = true
      taskList = true
      typographer = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
